### ISSUE TITLE
Android 10 实时投屏功能用不了

### ISSUE THREAD

**Issue by Kevin-liutianping** [alibaba/web-editor#72]
#### 描述：手机系统为Android 9 的时候还是可用的，后来把系统升级为10后，实时投屏功能就用不了，并且换了朋友的小米(系统版本也是Android 10)手机试了下，实时投屏也是用不了，其他的功能都是可以正常使用的。

**Comment by codeskyblue** [comment]
你电脑上的uiautomator2什么版本的？升级到最新的2.5.7试试

**Comment by Kevin-liutianping** [comment]
#### uiautomator2版本是2.57，weditor0版本.42。您这边Android 10 的机型是没有这个问题的是吧？

**Comment by Kevin-liutianping** [comment]
#### 我试过了好多方法。重新安装uiautomator2和weditor（都是最新版），以及重新init，可实时投屏这个功能还是不行。翔哥能帮忙解答下吗？拜托了！

**Comment by codeskyblue** [comment]
Minicap对Android Q支持的没有这么好

**Comment by trevorwang** [comment]
<img width="498" alt="Screen Shot 2020-09-25 at 10 58 30 AM" src="https://user-images.githubusercontent.com/121966/94221698-36b2a300-ff1e-11ea-8018-51799f62e570.png">


Android 10  模拟器上页面刷新不了 只有第一次链接的页面

**Comment by SusonJohn** [comment]
现在新版修复了嘛？ @codeskyblue

**Comment by codeskyblue** [comment]
模拟器就是这个样子，我默认不安装minicap。  @SusonJohn 更新一下uiautomator2，然后在`uiautomator2 init`一下，估计就可以了
