### ISSUE TITLE
已使用”python -m weditor“命令，仍然报错

### ISSUE THREAD

**Issue by arbaleast** [alibaba/web-editor#88]
![QQ截图20210401191054](https://user-images.githubusercontent.com/57560360/113285959-28ef3780-931e-11eb-9afa-8cc7afab3083.png)

**Comment by dolfly** [comment]
@arbaleast 可以试试 dolfly/weditor 这个版本的

**Comment by arbaleast** [comment]
> 
> 
> @arbaleast 可以试试 dolfly/weditor 这个版本的

谢谢回复，我试试

**Comment by zhaoshe** [comment]
@arbaleast 问题解决了吗？我也碰到一样的问题。。

**Comment by arbaleast** [comment]
> @arbaleast 问题解决了吗？我也碰到一样的问题。。
> 

更新weditor试试？

**Comment by arbaleast** [comment]
> @arbaleast 问题解决了吗？我也碰到一样的问题。。
> 

python3 -m weditor
listening on http://192.168.98.107:17310
[I 210425 17:15:33 web:2239] 200 GET / (127.0.0.1) 3.14ms
[I 210425 17:15:34 web:2239] 101 GET /ws/v1/python (127.0.0.1) 2.70ms
[I 210425 17:15:34 shell:172] create process pid: 1585591
[I 210425 17:15:34 web:2239] 200 GET /api/v1/version (127.0.0.1) 0.39ms
[W 210425 17:15:46 shell:206] websocket closed
[I 210425 17:15:46 shell:101] process quited with code -9

---
访问监听的IP
    listening on http://192.168.98.107:17310
而不是localhost:17310，能起作用。

**Comment by arbaleast** [comment]
看起来也不能解决，同样出现这个问题

**Comment by wangtaoyuan** [comment]
轻触浏览器缓存可以暂时解决
